# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "dobi-unstable-${version}";
  version = "2018-05-08";
  rev = "7cca562fb4df4d06d0b0107108478d3d434c775f";

  goPackagePath = "github.com/dnephin/dobi";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/dnephin/dobi";
    sha256 = "0pv622dgdpl2nd4yvhjx6pgr1cd2bz5v9pisiaxivh1n7x5y3nzq";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
