# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "dobi-unstable-${rev}";
  rev = "15cb0b6f9c7393ef2fa3113a621b25c3449e65f3";

  goPackagePath = "github.com/dnephin/dobi";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/dnephin/dobi";
    sha256 = "1jssqjmnaiwh6h94dal5rp73l329a810ni1s94jr8skp1d66hhk2";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
